const express = require('express');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

// Bot process state
let botProcess = null;
let botLogs = [];
const MAX_LOGS = 1000;

function timestamp() {
  return new Date().toLocaleString('id-ID', { hour12: false });
}

function addLog(msg, type = 'info') {
  botLogs.push({ time: timestamp(), msg, type });
  if (botLogs.length > MAX_LOGS) botLogs.shift();
}

// --- Config API ---
app.get('/api/config', (req, res) => {
  try {
    const data = fs.readFileSync(path.join(__dirname, 'configloket.json'), 'utf8');
    res.json({ success: true, data: JSON.parse(data) });
  } catch {
    res.json({ success: true, data: [{ api_key: '', telegram_bot_token: '', telegram_chat_id: '' }] });
  }
});

app.post('/api/config', (req, res) => {
  try {
    const { api_key, telegram_bot_token, telegram_chat_id } = req.body;
    const config = [{ api_key: api_key || '', telegram_bot_token: telegram_bot_token || '', telegram_chat_id: telegram_chat_id || '' }];
    fs.writeFileSync(path.join(__dirname, 'configloket.json'), JSON.stringify(config, null, 4), 'utf8');
    res.json({ success: true, message: 'Konfigurasi berhasil disimpan!' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal menyimpan: ' + e.message });
  }
});

// --- Data Input API ---
app.get('/api/datainput', (req, res) => {
  try {
    const data = fs.readFileSync(path.join(__dirname, 'datainput.txt'), 'utf8');
    res.json({ success: true, data: data.trim() });
  } catch {
    res.json({ success: true, data: '' });
  }
});

app.post('/api/datainput', (req, res) => {
  try {
    fs.writeFileSync(path.join(__dirname, 'datainput.txt'), req.body.data || '', 'utf8');
    res.json({ success: true, message: 'Data pembeli berhasil disimpan!' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal menyimpan: ' + e.message });
  }
});

// --- Cookie API (read-only, generated by bot after order) ---
app.get('/api/cookie', (req, res) => {
  try {
    const data = fs.readFileSync(path.join(__dirname, 'cookieLoket.txt'), 'utf8');
    res.json({ success: true, data: data.trim() });
  } catch {
    res.json({ success: true, data: '' });
  }
});

// --- Bot Control API ---
app.get('/api/bot/status', (req, res) => {
  res.json({
    success: true,
    running: botProcess !== null && !botProcess.killed,
    logs: botLogs.slice(-100)
  });
});

app.get('/api/bot/logs', (req, res) => {
  res.json({ success: true, logs: botLogs.slice(-300) });
});

app.post('/api/bot/logs/clear', (req, res) => {
  botLogs = [];
  res.json({ success: true, message: 'Log dibersihkan!' });
});

// --- Send input to bot (for interactive menus) ---
app.post('/api/bot/input', (req, res) => {
  if (!botProcess || botProcess.killed) {
    return res.json({ success: false, message: 'Bot tidak sedang berjalan!' });
  }
  try {
    const { text } = req.body;
    botProcess.stdin.write(text + '\n');
    addLog(`[INPUT] User memilih: ${text}`, 'info');
    res.json({ success: true, message: 'Input dikirim ke bot.' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal kirim input: ' + e.message });
  }
});

app.post('/api/bot/start', (req, res) => {
  if (botProcess && !botProcess.killed) {
    return res.json({ success: false, message: 'Bot sudah berjalan!' });
  }

  try {
    const { answers } = req.body || {};
    // answers = { mode, captcha, dataFile, totalTicket, keyword, keywordCadangan, kodeUndangan, showVa, linkEvent, waktu }
    const a = answers || {};
    botLogs = [];
    addLog('Memulai bot...', 'info');
    addLog(`Mode: ${a.mode || '1'} | Captcha: ${a.captcha || '1'} | Tiket: ${a.totalTicket || '1'}`, 'info');

    botProcess = spawn('node', ['loketbot.js'], {
      cwd: __dirname,
      env: { ...process.env },
      stdio: ['pipe', 'pipe', 'pipe']
    });

    // Queue of answers to send sequentially
    const answerQueue = [];
    let promptIndex = 0;

    // Build answer queue based on user inputs
    // 1. Pilih fitur bot (arrow select: 1-4)
    answerQueue.push({ type: 'arrow', value: parseInt(a.mode) || 1 });
    // 2. Pilih tipe CAPTCHA (arrow select: 1=Turnstile, 2=reCAPTCHA)
    answerQueue.push({ type: 'arrow', value: parseInt(a.captcha) || 1 });
    // 3. Pilih data pembeli (arrow select, biasanya 1)
    answerQueue.push({ type: 'arrow', value: parseInt(a.dataFile) || 1 });
    // 4. Total tiket (ketik angka)
    answerQueue.push({ type: 'text', value: a.totalTicket || '1' });
    // 5. Keyword tiket (ketik)
    answerQueue.push({ type: 'text', value: a.keyword || '' });
    // 6. Keyword cadangan (ketik)
    answerQueue.push({ type: 'text', value: a.keywordCadangan || '' });
    // 7. Kode undangan (ketik, bisa kosong)
    answerQueue.push({ type: 'text', value: a.kodeUndangan || '' });
    // 8. Tampilkan VA atau tidak (arrow select: 1=Ya, 2=Tidak)
    answerQueue.push({ type: 'arrow', value: parseInt(a.showVa) || 1 });
    // 9. Link event (ketik)
    answerQueue.push({ type: 'text', value: a.linkEvent || '' });
    // 10. Waktu (enter = langsung, atau ketik waktu)
    answerQueue.push({ type: 'text', value: a.waktu || '' });

    function sendNextAnswer() {
      if (promptIndex >= answerQueue.length) return;
      if (!botProcess || botProcess.killed) return;

      const answer = answerQueue[promptIndex];
      promptIndex++;

      setTimeout(() => {
        if (!botProcess || botProcess.killed) return;

        if (answer.type === 'arrow') {
          // Navigate with arrow down keys, then press enter
          for (let i = 1; i < answer.value; i++) {
            botProcess.stdin.write('\x1B[B'); // Arrow Down
          }
          botProcess.stdin.write('\r'); // Enter
        } else {
          // Type text + enter
          botProcess.stdin.write(answer.value + '\n');
        }

        addLog(`[AUTO-INPUT ${promptIndex}] ${answer.value || '(enter)'}`, 'success');
      }, 800);
    }

    botProcess.stdout.on('data', (data) => {
      const output = data.toString();
      output.split('\n').filter(l => l.trim()).forEach(line => {
        addLog(line, 'info');
      });

      // Detect prompts (? or >) and auto-answer
      if (output.includes('?') || output.includes('Pilih') || output.includes('Masuk') || output.includes('Input') || output.includes('>')) {
        sendNextAnswer();
      }
    });

    botProcess.stderr.on('data', (data) => {
      data.toString().split('\n').filter(l => l.trim()).forEach(line => {
        addLog(line, 'error');
      });
    });

    botProcess.on('close', (code) => {
      addLog(`Bot berhenti (kode: ${code})`, code === 0 ? 'success' : 'error');
      botProcess = null;
    });

    botProcess.on('error', (err) => {
      addLog('Gagal menjalankan bot: ' + err.message, 'error');
      botProcess = null;
    });

    res.json({ success: true, message: 'Bot dijalankan! Mengisi jawaban otomatis...' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal: ' + e.message });
  }
});

app.post('/api/bot/stop', (req, res) => {
  if (!botProcess || botProcess.killed) {
    return res.json({ success: false, message: 'Bot tidak sedang berjalan!' });
  }
  try {
    botProcess.kill('SIGTERM');
    addLog('Bot dihentikan oleh pengguna.', 'info');
    botProcess = null;
    res.json({ success: true, message: 'Bot dihentikan!' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal menghentikan: ' + e.message });
  }
});

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`\n  Sepurane Bot Dashboard`);
  console.log(`  ----------------------`);
  console.log(`  Buka browser: http://localhost:${PORT}`);
  console.log(`  Tekan Ctrl+C untuk berhenti\n`);
});
