const express = require('express');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));

// Bot process state
let botProcess = null;
let botLogs = [];
const MAX_LOGS = 1000;

function timestamp() {
  return new Date().toLocaleString('id-ID', { hour12: false });
}

function addLog(msg, type = 'info') {
  botLogs.push({ time: timestamp(), msg, type });
  if (botLogs.length > MAX_LOGS) botLogs.shift();
}

// --- Config API ---
app.get('/api/config', (req, res) => {
  try {
    const data = fs.readFileSync(path.join(__dirname, 'configloket.json'), 'utf8');
    res.json({ success: true, data: JSON.parse(data) });
  } catch {
    res.json({ success: true, data: [{ api_key: '', telegram_bot_token: '', telegram_chat_id: '' }] });
  }
});

app.post('/api/config', (req, res) => {
  try {
    const { api_key, telegram_bot_token, telegram_chat_id } = req.body;
    const config = [{ api_key: api_key || '', telegram_bot_token: telegram_bot_token || '', telegram_chat_id: telegram_chat_id || '' }];
    fs.writeFileSync(path.join(__dirname, 'configloket.json'), JSON.stringify(config, null, 4), 'utf8');
    res.json({ success: true, message: 'Konfigurasi berhasil disimpan!' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal menyimpan: ' + e.message });
  }
});

// --- Data Input API ---
app.get('/api/datainput', (req, res) => {
  try {
    const data = fs.readFileSync(path.join(__dirname, 'datainput.txt'), 'utf8');
    res.json({ success: true, data: data.trim() });
  } catch {
    res.json({ success: true, data: '' });
  }
});

app.post('/api/datainput', (req, res) => {
  try {
    fs.writeFileSync(path.join(__dirname, 'datainput.txt'), req.body.data || '', 'utf8');
    res.json({ success: true, message: 'Data pembeli berhasil disimpan!' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal menyimpan: ' + e.message });
  }
});

// --- Cookie API (read-only, generated by bot after order) ---
app.get('/api/cookie', (req, res) => {
  try {
    const data = fs.readFileSync(path.join(__dirname, 'cookieLoket.txt'), 'utf8');
    res.json({ success: true, data: data.trim() });
  } catch {
    res.json({ success: true, data: '' });
  }
});

// --- Bot Control API ---
app.get('/api/bot/status', (req, res) => {
  res.json({
    success: true,
    running: botProcess !== null && !botProcess.killed,
    logs: botLogs.slice(-100)
  });
});

app.get('/api/bot/logs', (req, res) => {
  res.json({ success: true, logs: botLogs.slice(-300) });
});

app.post('/api/bot/logs/clear', (req, res) => {
  botLogs = [];
  res.json({ success: true, message: 'Log dibersihkan!' });
});

// --- Send input to bot (for interactive menus) ---
app.post('/api/bot/input', (req, res) => {
  if (!botProcess || botProcess.killed) {
    return res.json({ success: false, message: 'Bot tidak sedang berjalan!' });
  }
  try {
    const { text } = req.body;
    botProcess.stdin.write(text + '\n');
    addLog(`[INPUT] User memilih: ${text}`, 'info');
    res.json({ success: true, message: 'Input dikirim ke bot.' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal kirim input: ' + e.message });
  }
});

app.post('/api/bot/start', (req, res) => {
  if (botProcess && !botProcess.killed) {
    return res.json({ success: false, message: 'Bot sudah berjalan!' });
  }

  try {
    const { answers } = req.body || {};
    const a = answers || {};
    botLogs = [];
    addLog('Memulai bot...', 'info');
    addLog(`Mode: ${a.mode || '1'} | Captcha: ${a.captcha || '1'} | Tiket: ${a.totalTicket || '1'}`, 'info');

    botProcess = spawn('node', ['loketbot.js'], {
      cwd: __dirname,
      env: { ...process.env },
      stdio: ['pipe', 'pipe', 'pipe']
    });

    // Simple sequential approach: send answers with fixed delays
    const selectedBuyers = a.selectedBuyers || [1]; // Array of 1-based indices
    
    const answerQueue = [
      { type: 'arrow', value: parseInt(a.mode) || 1, label: 'Fitur bot', delay: 2000 },
      { type: 'checkbox', value: parseInt(a.captcha) || 1, label: 'Captcha', delay: 2000 },
      { type: 'multicheck', values: selectedBuyers, total: selectedBuyers.length, label: 'Data pembeli', delay: 2500 },
      { type: 'text', value: a.totalTicket || '1', label: 'Total tiket', delay: 1500 },
      { type: 'text', value: a.keyword || '', label: 'Keyword tiket', delay: 1500 },
      { type: 'text', value: a.keywordCadangan || '', label: 'Keyword cadangan', delay: 1500 },
      { type: 'text', value: a.kodeUndangan || '', label: 'Kode undangan', delay: 1500 },
      { type: 'arrow', value: parseInt(a.showVa) || 1, label: 'Tampilkan VA', delay: 2000 },
    ];

    // Mode-specific prompts (after VA selection)
    const mode = parseInt(a.mode) || 1;
    if (mode === 2) {
      answerQueue.push({ type: 'text', value: a.domain || '', label: 'Domain', delay: 1500 });
      answerQueue.push({ type: 'text', value: a.clue || '', label: 'Clue', delay: 1500 });
      answerQueue.push({ type: 'text', value: a.day || '', label: 'Day', delay: 1500 });
    } else {
      answerQueue.push({ type: 'text', value: a.linkEvent || '', label: 'Link event/widget', delay: 1500 });
    }
    answerQueue.push({ type: 'text', value: a.waktu || '', label: 'Waktu', delay: 1500 });
    answerQueue.push({ type: 'text', value: a.captchaBefore || '10', label: 'Captcha detik sebelum', delay: 1500 });

    // Send all answers sequentially with delays
    let totalDelay = 3000; // Initial wait for bot to start and show first prompt
    
    answerQueue.forEach((answer, idx) => {
      setTimeout(() => {
        if (!botProcess || botProcess.killed) return;

        if (answer.type === 'arrow') {
          // Arrow down to navigate, then enter
          for (let i = 1; i < answer.value; i++) {
            botProcess.stdin.write('\x1B[B');
          }
          setTimeout(() => {
            if (botProcess && !botProcess.killed) botProcess.stdin.write('\r');
          }, 150);
        } else if (answer.type === 'checkbox') {
          // Arrow down to navigate, space to select, then enter
          for (let i = 1; i < answer.value; i++) {
            botProcess.stdin.write('\x1B[B');
          }
          setTimeout(() => {
            if (!botProcess || botProcess.killed) return;
            botProcess.stdin.write(' ');
            setTimeout(() => {
              if (botProcess && !botProcess.killed) botProcess.stdin.write('\r');
            }, 150);
          }, 150);
        } else if (answer.type === 'multicheck') {
          // Multi-select: navigate and space each selected item, then enter
          // Items are 1-based indices. We start at position 1 (top).
          const sorted = answer.values.slice().sort((a,b) => a-b);
          let currentPos = 1;
          let stepDelay = 0;
          
          sorted.forEach((itemIdx) => {
            const stepsDown = itemIdx - currentPos;
            setTimeout(() => {
              if (!botProcess || botProcess.killed) return;
              // Navigate down to the item
              for (let i = 0; i < stepsDown; i++) {
                botProcess.stdin.write('\x1B[B');
              }
              // Space to toggle selection
              setTimeout(() => {
                if (botProcess && !botProcess.killed) botProcess.stdin.write(' ');
              }, 100);
            }, stepDelay);
            stepDelay += 300;
            currentPos = itemIdx;
          });
          
          // After selecting all, press enter
          setTimeout(() => {
            if (botProcess && !botProcess.killed) botProcess.stdin.write('\r');
          }, stepDelay + 200);
        } else {
          // Type text + enter
          botProcess.stdin.write(answer.value + '\n');
        }

        addLog(`[AUTO-INPUT ${idx+1}/${answerQueue.length}] ${answer.label}: ${answer.value || '(enter)'}`, 'success');
      }, totalDelay);
      
      totalDelay += answer.delay;
    });

    // Simple stdout/stderr logging
    botProcess.stdout.on('data', (data) => {
      const clean = data.toString().replace(/\x1B\[[0-9;]*[A-Za-z]/g, '');
      clean.split('\n').filter(l => l.trim()).forEach(line => {
        addLog(line.trim(), 'info');
      });
    });

    botProcess.stderr.on('data', (data) => {
      data.toString().split('\n').filter(l => l.trim()).forEach(line => {
        const clean = line.replace(/\x1B\[[0-9;]*[A-Za-z]/g, '').trim();
        if (clean) addLog(clean, 'error');
      });
    });

    botProcess.on('close', (code) => {
      addLog(`Bot berhenti (kode: ${code})`, code === 0 ? 'success' : 'error');
      botProcess = null;
    });

    botProcess.on('error', (err) => {
      addLog('Gagal menjalankan bot: ' + err.message, 'error');
      botProcess = null;
    });

    res.json({ success: true, message: 'Bot dijalankan! Mengisi jawaban otomatis...' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal: ' + e.message });
  }
});

app.post('/api/bot/stop', (req, res) => {
  if (!botProcess || botProcess.killed) {
    return res.json({ success: false, message: 'Bot tidak sedang berjalan!' });
  }
  try {
    botProcess.kill('SIGTERM');
    addLog('Bot dihentikan oleh pengguna.', 'info');
    botProcess = null;
    res.json({ success: true, message: 'Bot dihentikan!' });
  } catch (e) {
    res.status(500).json({ success: false, message: 'Gagal menghentikan: ' + e.message });
  }
});

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`\n  Sepurane Bot Dashboard`);
  console.log(`  ----------------------`);
  console.log(`  Buka browser: http://localhost:${PORT}`);
  console.log(`  Tekan Ctrl+C untuk berhenti\n`);
});
